# Generated by Django 4.1.3 on 2022-11-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ElementSystem', '0002_alter_element_image_alter_rarity_image'),
        ('GeneralSystem', '0003_alter_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('expiration', models.DateTimeField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElementSystem.element')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralSystem.player')),
            ],
        ),
    ]
