# Generated by Django 4.1.3 on 2022-12-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElementSystem', '0002_alter_element_image_alter_rarity_image'),
        ('GameAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ShipID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaceship/picture/')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ElementSystem.element')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ElementSystem.rarity')),
            ],
        ),
    ]
