# Generated by Django 4.1.3 on 2022-11-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
