# Generated by Django 4.1.3 on 2022-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('NETWORK_NAME', models.CharField(default='Smart Chain', max_length=100)),
                ('RPC_URL', models.CharField(default='https://bsc-dataseed.binance.org/', max_length=100)),
                ('CHAIN_ID', models.DecimalField(decimal_places=0, default=56, max_digits=10)),
                ('SYMBOL', models.CharField(default='BNB', max_length=100)),
                ('EXPLORER_URL', models.CharField(default='https://bscscan.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoralisAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('API_KEY', models.CharField(max_length=100)),
                ('DAPP_URL', models.CharField(max_length=100)),
                ('APP_ID', models.CharField(max_length=100)),
                ('MASTER_KEY', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoralisAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('DOMAIN', models.CharField(max_length=100)),
                ('CHAIN_ID', models.DecimalField(decimal_places=0, default=56, max_digits=10)),
                ('STATEMENT', models.CharField(default='Please confirm', max_length=100)),
                ('URI', models.CharField(max_length=100)),
                ('EXPIRATION_TIME', models.DecimalField(decimal_places=0, default=604800, max_digits=10)),
                ('TIMEOUT', models.DecimalField(decimal_places=0, default=15, max_digits=10)),
            ],
        ),
    ]
