# Generated by Django 4.1.3 on 2022-11-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralSystem', '0002_player_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_connection', models.CharField(max_length=100)),
                ('key_confirmation', models.CharField(max_length=100)),
                ('key_access', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GeneralSystem.player')),
            ],
        ),
    ]
