# Generated by Django 4.1.3 on 2022-12-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameAPI', '0002_spaceship'),
        ('SecuritySystem', '0002_activesession_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='spaceship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GameAPI.spaceship'),
        ),
    ]
